In [1]:
print("Hello World")

Hello World


In [15]:
#Array
import numpy as np
list = [0, 1, 2]
print(list)
array = np.array(list)
array



[0, 1, 2]


array([0, 1, 2])

In [23]:
#List to 2D Array
list = [[1,2,3],[4,5,6]]
list
array_2d_matrix = np.array(list)
print(array_2d_matrix)

[[1 2 3]
 [4 5 6]]


In [26]:
#Tuple to Array 
my_tuple = (-1,0,1)
my_array = np.array(my_tuple) 
my_array


array([-1,  0,  1])

In [29]:
#
#
#ARRAY CREATION USING Numpy's Built In Methods
#
#

In [33]:
''' arange()

* arange() is very much similar to Python function range() 
* Syntax: arange([start,] stop[, step,], dtype=None) 
* Return evenly spaced values within a given interval.

*Press shift+tab for the documentation.*'''

' arange()\n\n* arange() is very much similar to Python function range() <br>\n* Syntax: arange([start,] stop[, step,], dtype=None) <br>\n* Return evenly spaced values within a given interval. <br>\n\n*Press shift+tab for the documentation.*'

In [5]:
#linespace() => Return evenly spaced numbers over a specified interval.
import numpy as np
my_linspace = np.linspace(9, 15, 20, retstep=True)
my_linspace

(array([ 9.        ,  9.31578947,  9.63157895,  9.94736842, 10.26315789,
        10.57894737, 10.89473684, 11.21052632, 11.52631579, 11.84210526,
        12.15789474, 12.47368421, 12.78947368, 13.10526316, 13.42105263,
        13.73684211, 14.05263158, 14.36842105, 14.68421053, 15.        ]),
 0.3157894736842105)