<a href="https://colab.research.google.com/github/mishad01/Deep-Learning-and-Machine-Learning/blob/main/Pattern%20Recognition/Lab4_MLP_for_image_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [163]:
import numpy as np
from tensorflow.keras.datasets import mnist
import matplotlib.pyplot as plt

In [164]:
(X_train, y_train), (X_test, y_test) = mnist.load_data() #predefined 80 train and 20 test
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [165]:
X_train.shape, y_train.shape

((60000, 28, 28), (60000,))

In [166]:
X_test.shape, y_test.shape #((10000, 28, 28), (10000,)) -> 1000 image, 28 row and 28 column // (10000,) -> 1000 label is basically column

((10000, 28, 28), (10000,))

#Converting to 1D

In [167]:
input_size = X_train.shape[1] * X_train.shape[2]
input_size

784

In [168]:
X_train = np.reshape(X_train,[-1,input_size])
X_train.shape

(60000, 784)

In [169]:
X_test = np.reshape(X_test,[-1,input_size])
X_test.shape

(10000, 784)

#Datasets Deails

In [170]:
unique, count = np.unique(y_train, return_counts=True)
print(unique,count)

[0 1 2 3 4 5 6 7 8 9] [5923 6742 5958 6131 5842 5421 5918 6265 5851 5949]


#Dataset Samples

In [171]:
index = [10,16,1888,2000,2005]
images = X_train[index]
labels = y_train[index]
labels.shape

(5,)

#Plotting image sampls

In [172]:
# import matplotlib.pyplot as plt

# # Example data (replace with your actual data)
# # index = range(15)  # Assuming there are 15 images
# # images = [image_array1, image_array2, ..., image_array15]  # Your images

# plt.figure(figsize=(10, 10))  # Image size 10x10 inches

# for i in range(len(index)):
#     plt.subplot(5, 3, i+1)
#     plt.imshow(images[i], cmap='gray')  # Display the image
#     plt.axis('off')  # Hide axis for cleaner look
#     plt.text(5, 5, labels[i], color='red', fontsize=12)  # Add a side comment (adjust as needed)

# plt.tight_layout()  # Adjust layout to prevent overlapping
# plt.show()


#Normalization

In [173]:
X_train = X_train/255
X_test = X_test/255

#One Hot Encoding
**One-Hot Encoding** is a method to convert categorical data into binary vectors, where each category is represented by a vector of 0s and 1s. Each category gets its own column, and a 1 is placed in the column corresponding to the category, while all other columns have 0s.

### Example:
For a "Color" variable with categories: Red, Blue, Green:
- **Red** → [1, 0, 0]
- **Blue** → [0, 1, 0]
- **Green** → [0, 0, 1]

### Why Use It:
- Makes categorical data usable for machine learning models.
- Prevents the model from assuming any order in categories.

### In Python (using pandas):
```python
import pandas as pd
df = pd.DataFrame({'Color': ['Red', 'Blue', 'Green']})
df_encoded = pd.get_dummies(df, columns=['Color'])
print(df_encoded)
```

This will create separate columns for each category, with 1s and 0s indicating the presence of each category.

In [174]:
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
y_train[:3]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

#Model Building


In [175]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

In [176]:
model = Sequential()
model.add(Dense(256,activation='relu',input_dim=input_size))
model.add(Dense(256,activation='relu'))
model.add(Dense(10,activation='softmax'))


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [177]:
model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_13 (Dense)                     │ (None, 256)                 │         200,960 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_14 (Dense)                     │ (None, 256)                 │          65,792 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_15 (Dense)                     │ (None, 10)                  │           2,570 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 269,322 (1.03 MB)

 Trainable params: 269,322 (1.03 MB)

 Non-trainable params: 0 (0.00 B)

In [185]:
model.compile(loss = 'categorical_crossentropy',optimizer='Adam',metrics=["accuracy"])


In [191]:
model.fit(X_train,y_train,epochs=20,batch_size=32)

Epoch 1/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9896 - loss: 0.0412
Epoch 2/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9947 - loss: 0.0179
Epoch 3/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9953 - loss: 0.0142
Epoch 4/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9959 - loss: 0.0139
Epoch 5/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9963 - loss: 0.0121
Epoch 6/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9965 - loss: 0.0110
Epoch 7/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9948 - loss: 0.0171
Epoch 8/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9976 - loss: 0.0077
Epoch 9/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9968 - loss: 0.0100
Epoch 10/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9967 - loss: 0.0108
Epoch 11/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9972 - loss: 0.0085
Epoch 12/20
1875/1875 ━━━━

In [192]:
loss, accuracy = model.evaluate(X_test,y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9754 - loss: 0.2223
Test Loss: 0.17076964676380157
Test Accuracy: 0.9794999957084656


In [188]:
y_pred = y_prob.argmax(axis=1)
