<a href="https://colab.research.google.com/github/mishad01/Data-Science-Machine-Learning/blob/main/7.NumPy_Essentials_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

A vector is one dimensional array of numbers. It represents as row or column.<br>
Example :  
Row Vector, V = [1, 2, 3]<br>
|1| = V, 90Column Vector<br>
|2|<br>
|3|<br>


#Matrix
A matrix is a two dimensional array of numbers arranges in rows and columns.<br>
Example :<br>
|1,2,3|<br>
|4,5,6|<br>

#Summary of Differences:
A vector is 1D (either a row or column).<br>
A matrix is 2D (multiple rows and columns).


**2. How to import `NumPy` library?**

In [ ]:
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [ ]:
list_1 = [1,2,3,4,5]

In [9]:
import numpy as np

list_1 = np.array(list_1)
print(list_1)

[1 2 3 4 5]


**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [10]:
np.arange(0,6)

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [13]:
zero_array = np.empty (5)
zero_array.fill(0)
zero_array

array([0., 0., 0., 0., 0.])

**6. Generate the following `matrix`.**

In [ ]:
# To avoid overwriting the output, please code here

In [18]:
matrix = np.empty(12)
matrix.fill(0)
matrix = matrix.reshape(3,4)
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [ ]:
# To avoid overwriting the output, please code here

In [22]:
arr = np.linspace(1,1,5)
arr

array([1., 1., 1., 1., 1.])

**8. Generate an array of "5" tens.**

In [27]:
arr = np.full(5,10)

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [30]:
arr = np.arange(52,100,2)
arr

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [33]:
arr = np.linspace(0,1,10)
print(arr)
step_size = arr[1]-arr[0]
print(step_size)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
0.1111111111111111


(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [34]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr.shape = (5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [44]:
arr = np.arange(0.1,2.6,0.1)
arr.reshape(5,5)

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [54]:
arr = np.linspace(0,24,25,dtype=int)
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

In [ ]:
# Please consult the lectures.
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.

**15. How to generate a single random integer number using NumPy built-in function?**

In [58]:
ran = np.random.randint(0,10,5)
ran

array([4, 9, 8, 3, 2])

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [66]:
arr = np.random.rand(7,5)
arr

array([[0.10526073, 0.0245383 , 0.34646374, 0.42210203, 0.84117667],
       [0.54221582, 0.82377044, 0.8287486 , 0.6782069 , 0.39370263],
       [0.91385108, 0.48945021, 0.4257851 , 0.69259078, 0.11480744],
       [0.08823322, 0.60499675, 0.50741154, 0.91185369, 0.66140752],
       [0.94612489, 0.48185364, 0.29044414, 0.84467375, 0.39415406],
       [0.31549328, 0.81245177, 0.61138833, 0.30291354, 0.03030184],
       [0.48211219, 0.26542853, 0.35135966, 0.92083621, 0.69834675]])

[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for
identity matrix.**

In [67]:
arr = 5*np.identity(5)
arr

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck