<a href="https://colab.research.google.com/github/mishad01/Data-Science-Machine-Learning/blob/main/7_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Array
import numpy as np
list = [0, 1, 2]
print(list)
array = np.array(list)
array


[0, 1, 2]


array([0, 1, 2])

In [ ]:
#List to 2D Array
list = [[1,2,3],[4,5,6]]
list
array_2d_matrix = np.array(list)
print(array_2d_matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Tuple to Array
my_tuple = (-1,0,1)
my_array = np.array(my_tuple)
my_array


array([-1,  0,  1])

#ARRAY CREATION USING Numpy's Built In Methods


#arrange()
#Parameters:
1. Start (1):
This is the starting value of the sequence. The first number in the generated array will be 1.

2. Stop (2):
This is the end value of the sequence. However, it is exclusive, meaning 2 is not included in the generated array.

3. Step (0.1):
This is the spacing between consecutive values in the sequence. In this case, each number in the array is 0.1 greater than the previous number.

In [ ]:
num = np.arange(10)
num

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#we can give steps also
np.arange(3,10,2)


array([3, 5, 7, 9])

In [ ]:
import numpy as np
my_arange = np.arange(1, 2, 0.1)
my_arange


array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [ ]:
np.arange(0,10,2.1, dtype= float)

array([0. , 2.1, 4.2, 6.3, 8.4])

In [ ]:
x = np.arange(1, 2, 0.1)
print(x.shape) #length basically
#The array has 10 elements. Since it is 1-dimensional, its shape is represented as a tuple with one value:

(10,)


#x.shape == length

In [ ]:
x = np.arange(0,16)
x.shape


(16,)

#reshape -> makes dimension, basically kinda creates matrix

In [ ]:
x.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
x.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x.reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

# Breaking it down:
Original Shape of x:

If x is a 1-dimensional array with 4 * 2 * 2 = 16 elements, you can reshape it into a 3-dimensional array with shape (4, 2, 2).
Understanding Dimensions:

The target shape (4, 2, 2) means:
4 blocks of size (2, 2)
Each block has 2 rows and 2 columns.
Conditions for Reshaping:

The total number of elements in x must match the total number of elements in the target shape.
In this case:
4
×
2
×
2
=
16
4×2×2=16, so x must have exactly 16 elements.

In [46]:
y = x.reshape(4,2,2) #here 4 is number of matrix and 2,2 is matrix
y

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [47]:
y.shape

(4, 2, 2)

#When there is () , it will be function. Otherwise it will be attributes

#linespace()
1.   Return evenly spaced numbers over a specified interval..
2.   Return evenly spaced numbers over a specified interval..
#What linespace does is it divides a number. For an example linspace(0,10,4) = > 0., 3.33333333, 6.66666667,10.  

#Here from 0 to 10, 10 is divided into 4 parts


np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
1. start: The starting value of the sequence.
2. stop: The ending value of the sequence.
3. num: The number of evenly spaced values to generate (default is 50).
4. endpoint: If True (default), the stop value is included in the sequence. If False, the sequence ends just before stop.
5. retstep: If True, it also returns the spacing (step) between consecutive 7.  numbers in the array.
6. dtype: The data type of the output array (optional).

In [ ]:
#linespace() => Return evenly spaced numbers over a specified interval.

import numpy as np
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [ ]:
np.linspace(1,2,10) # 1-D array

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [ ]:
x =  [[1,2,3],[4,5,6]]
np.array(x)

array([[1, 2, 3],
       [4, 5, 6]])

#Random
We can also create arrays with random numbers using Numpy's built-in functions in Random module.
np.random. and then press tab for the options with random

#rand()

In [48]:
np.random.rand(4) #1-D array with 3 (n-1) elements

array([0.79821178, 0.110919  , 0.09623603, 0.47029759, 0.81971694])

In [51]:
np.random.rand(2,2) #row,col based random values

array([[0.43435358, 0.65717478],
       [0.57824889, 0.3187728 ]])

#randnint()

In [57]:
np.random.randint(5,10,10) #np.random.randint(start,begining,number of random number)

array([5, 9, 5, 8, 9, 8, 7, 6, 9, 9])

In [58]:
np.random.randint(5,10,10).reshape(2,5) #Dimension

array([[9, 7, 9, 6, 8],
       [9, 7, 9, 9, 8]])

In [59]:
array = np.random.randint(low = 1,high = 10,size = [5,8])
array

array([[7, 4, 7, 1, 3, 4, 4, 4],
       [8, 6, 1, 8, 9, 9, 9, 2],
       [6, 4, 5, 8, 7, 5, 6, 1],
       [6, 7, 8, 6, 3, 8, 6, 5],
       [2, 5, 2, 4, 6, 4, 8, 3]])

## Array Methods & Attributes
Some important Methods and Attributes are important to know:<br>

### Methods:
* reshape(), max(), min(), argmax(), argmin()<br>

In [61]:
array_ranInt = np.random.randint(0,100,10)
array_ranInt

array([33, 85, 12, 86, 91, 28, 76, 53, 10,  1])

In [63]:
array_ranInt.min()

1

In [64]:
array_ranInt.max()

91

# `argmax()` & `argmin()`
To find the index locations of max and min values in array

In [65]:
array_ranInt.argmax()

4

In [66]:
array_ranInt.argmin()

9

### Attributes
* `size, shape, dtype`

In [74]:
arr_arange = np.arange(16)
arr_arange


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [73]:
arr_arange.shape

(16,)

In [76]:
arr_arange.size

16

In [78]:
# Size of the array
arr_arange.itemsize #byte

8

In [79]:
arr_arange.dtype

dtype('int64')

In [83]:
arr_arange.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

###  Indexing & slicing 2-D arrays (matrices)

Lets create an array with 24 elements using arange() and convert it to 2D matrix using "shape".<br>
*note, 6 x 4 = 24*

In [84]:
array_2d = np.arange(24)
array_2d = array_2d.reshape(6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [89]:
array_ld= np.array([-10,-2, 0, 2, 17, 106,200])
array_ld
array_ld[1]
#Getting range value
array_ld[0:3]

array([-10,  -2,   0])

In [90]:
array_ld[-2] #using -ve index

106