<a href="https://colab.research.google.com/github/mishad01/Data-Science-Machine-Learning/blob/main/7_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Array
import numpy as np
list = [0, 1, 2]
print(list)
array = np.array(list)
array


[0, 1, 2]


array([0, 1, 2])

In [2]:
#List to 2D Array
list = [[1,2,3],[4,5,6]]
list
array_2d_matrix = np.array(list)
print(array_2d_matrix)

[[1 2 3]
 [4 5 6]]


In [3]:
#Tuple to Array
my_tuple = (-1,0,1)
my_array = np.array(my_tuple)
my_array


array([-1,  0,  1])

#ARRAY CREATION USING Numpy's Built In Methods


#linespace()
1.   Return evenly spaced numbers over a specified interval..
2.   Return evenly spaced numbers over a specified interval..




np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
1. start: The starting value of the sequence.
2. stop: The ending value of the sequence.
3. num: The number of evenly spaced values to generate (default is 50).
4. endpoint: If True (default), the stop value is included in the sequence. If False, the sequence ends just before stop.
5. retstep: If True, it also returns the spacing (step) between consecutive 7.  numbers in the array.
6. dtype: The data type of the output array (optional).

In [16]:
#linespace() => Return evenly spaced numbers over a specified interval.
import numpy as np
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(1,2,10) # 1-D array

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

#arrange()

In [12]:
import numpy as np
my_arange = np.arange(1, 2, 0.1)
my_arange

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])